### ISSUE TITLE
DSLR as webcam

### ISSUE THREAD

**Issue by Erstus** [jesperpedersen/entangle#1]
Hi!

First of all, I really appreciate how well Entangle works and I'm hoping, that it helps to solve a problem I'm having. I want to use my DSLR as a webcam on Linux and Entangle has got me closer than ever.

I just set my camera to video mode and press continuous preview button in Entangle and it works! But i need this feed to be accessible in another application.

I noticed, that i can save a preview image instead of triggering the camera, so maybe i can save one image over-and-over each frame, but it would be even better to just redirect the feed into /dev/video0. Creating a plugin for this seems reasonable, but currently there's some problem with that.(described here: https://gna.org/bugs/?25176)

Any thoughts?

**Comment by jesperpedersen** [comment]
Please, post your question on the mailing list instead:

https://mail.gna.org/listinfo/entangle-devel/
